export const states: Record<string, string> = {
  '/andhra-pradesh': 'Andhra Pradesh',
  '/arunachal-pradesh': 'Arunachal Pradesh',
  '/assam': 'Assam',
  '/bihar': 'Bihar',
  '/chhattisgarh': 'Chhattisgarh',
  '/goa': 'Goa',
  '/gujarat': 'Gujarat',
  '/haryana': 'Haryana',
  '/himachal-pradesh': 'Himachal Pradesh',
  '/jharkhand': 'Jharkhand',
  '/karnataka': 'Karnataka',
  '/kerala': 'Kerala',
  '/madhya-pradesh': 'Madhya Pradesh',
  '/maharashtra': 'Maharashtra',
  '/manipur': 'Manipur',
  '/meghalaya': 'Meghalaya',
  '/mizoram': 'Mizoram',
  '/nagaland': 'Nagaland',
  '/odisha': 'Odisha',
  '/punjab': 'Punjab',
  '/rajasthan': 'Rajasthan',
  '/sikkim': 'Sikkim',
  '/tamil-nadu': 'Tamil Nadu',
  '/telangana': 'Telangana',
  '/tripura': 'Tripura',
  '/uttar-pradesh': 'Uttar Pradesh',
  '/uttarakhand': 'Uttarakhand',
  '/west-bengal': 'West Bengal',
  '/delhi': 'Delhi',
  '/jammu-kashmir': 'Jammu & Kashmir',
  '/ladakh': 'Ladakh',
  '/chandigarh': 'Chandigarh',
  '/puducherry': 'Puducherry',
  '/andaman-nicobar': 'Andaman & Nicobar',
  '/lakshadweep': 'Lakshadweep',
  '/dadra-nagar-haveli': 'Dadra & Nagar Haveli',
  '/kabaddi': 'Kabaddi Matches Latest Updates'
};
